export enum CountryCode {
  AL = '+355', // Albania
  AD = '+376', // Andorra
  AT = '+43',  // Austria
  BY = '+375', // Belarus
  BE = '+32',  // Belgium
  BA = '+387', // Bosnia and Herzegovina
  BG = '+359', // Bulgaria
  HR = '+385', // Croatia
  CY = '+357', // Cyprus
  CZ = '+420', // Czech Republic
  DK = '+45',  // Denmark
  EE = '+372', // Estonia
  FI = '+358', // Finland
  FR = '+33',  // France
  DE = '+49',  // Germany
  GR = '+30',  // Greece
  HU = '+36',  // Hungary
  IS = '+354', // Iceland
  IE = '+353', // Ireland
  IT = '+39',  // Italy
  LV = '+371', // Latvia
  LI = '+423', // Liechtenstein
  LT = '+370', // Lithuania
  LU = '+352', // Luxembourg
  MT = '+356', // Malta
  MD = '+373', // Moldova
  MC = '+377', // Monaco
  ME = '+382', // Montenegro
  NL = '+31',  // Netherlands
  MK = '+389', // North Macedonia
  NO = '+47',  // Norway
  PL = '+48',  // Poland
  PT = '+351', // Portugal
  RO = '+40',  // Romania
  RU = '+7',   // Russia (partial Europe)
  SM = '+378', // San Marino
  RS = '+381', // Serbia
  SK = '+421', // Slovakia
  SI = '+386', // Slovenia
  ES = '+34',  // Spain
  SE = '+46',  // Sweden
  CH = '+41',  // Switzerland
  UA = '+380', // Ukraine
  GB = '+44',  // United Kingdom
  VA = '+379', // Vatican City
}
